const outlandishResponses = [
  '"Proceed only if your reflective belt glows with purpose."',
  '"Affirmative. The squadron commander sensed your initiative from afar."',
  '"Negative. A rogue cadet flight has claimed this decision."',
  '"Yes—but only after a proper safety briefing to the nearest chair."',
  '"The forecast predicts a 92% chance of CAPF paperwork."',
  '"Decision delayed: Wing is consulting the sacred regulations binder."',
  '"Absolutely—your blues are perfectly pressed in spirit."',
  '"No. The Safety Officer felt a disturbance."',
  '"Outcome unclear. Request guidance from the nearest Lt Col."',
  '"Yes—if you can recite CAPR 39-1 from memory."',
  '"No—the uniform inspector is watching."',
  '"Affirmative. Ops already volunteered you for it."',
  '"Negative. Logistics lost the answer in a supply closet."',
  '"Yes—after submitting it through eServices three times."',
  '"No—your eServices session expired mid-decision."',
  '"Absolutely—provided you hydrate and change your socks."',
  '"Denied—missing one obscure online training module."',
  '"Yes—after the third “final” version is uploaded."',
  '"No—the printer has jammed your destiny."',
  '"Affirmative. The chain of command nodded silently."',
  '"Negative. The chain of command is tangled."',
  '"Yes—if your gig line is spiritually aligned."',
  '"No—your gig line has betrayed you."',
  '"Absolutely—after a 45-slide PowerPoint briefing."',
  '"Denied—PowerPoint lacked transitions."',
  '"Yes—if you say “per CAP regulation” confidently."',
  '"No—you forgot to cite the reg."',
  '"Affirmative. The Ops Quals system smiles upon you."',
  '"Negative. Ops Quals has no record of this."',
  '"Yes—after Group forwards it to Wing."',
  '"No—Wing forwarded it back to Group."',
  '"Absolutely—your boots shine bright enough."',
  '"Denied—boots reflect insufficient enthusiasm."',
  '"Yes—if you salute with dramatic precision."',
  '"No—your salute lacked conviction."',
  '"Affirmative. The Safety briefing was thorough."',
  '"Negative. Safety wants another briefing."',
  '"Yes—if you bring snacks to the meeting."',
  '"No—no snacks, no approval."',
  '"Absolutely—Finance shrugged “sure.”"',
  '"Denied—Finance frowned ominously."',
  '"Yes—after the meeting about the meeting."',
  '"No—the meeting spawned three more meetings."',
  '"Affirmative. The mission scanner approves."',
  '"Negative. The mission scanner has concerns."',
  '"Yes—if the radio check is loud and clear."',
  '"No—radio check came back “vibes only.”"',
  '"Absolutely—your reflective belt is glowing."',
  '"Denied—reflective belt not visible from orbit."',
  '"Yes—after a dramatic “roger that.”"',
  '"No—you said “copy” with doubt."',
  '"Affirmative. The cadet commander believes in you."',
  '"Negative. The cadet commander raised an eyebrow."',
  '"Yes—if you march with confidence."',
  '"No—you marched slightly left of destiny."',
  '"Absolutely—your cover is perfectly squared."',
  '"Denied—cover tilted 2 degrees off."',
  '"Yes—if you check in on the net properly."',
  '"No—you stepped on someone’s transmission."',
  '"Affirmative. The ICS forms are pleased."',
  '"Negative. The ICS forms demand sacrifice."',
  '"Yes—after completing one more online course."',
  '"No—course link is broken."',
  '"Absolutely—your email had all attachments."',
  '"Denied—attachment was missing."',
  '"Yes—if you CC literally everyone."',
  '"No—you forgot one critical CC."',
  '"Affirmative. The SUI gods are satisfied."',
  '"Negative. The SUI gods demand documentation."',
  '"Yes—after the suspenseful loading circle ends."',
  '"No—the loading circle persists."',
  '"Absolutely—your CAPID has power."',
  '"Denied—CAPID not recognized by fate."',
  '"Yes—if you stand at parade rest first."',
  '"No—you skipped straight to business."',
  '"Affirmative. The van is fueled and ready."',
  '"Negative. The van has questions."',
  '"Yes—if the GPS cooperates."',
  '"No—the GPS chose chaos."',
  '"Absolutely—your mission number is valid."',
  '"Denied—mission number expired mysteriously."',
  '"Yes—after Ops signs off."',
  '"No—Ops is “looking into it.”"',
  '"Affirmative. The uniform gods approve."',
  '"Negative. The uniform gods are displeased."',
  '"Yes—if your ribbons are perfectly aligned."',
  '"No—one ribbon is slightly crooked."',
  '"Absolutely—your boots echo authority."',
  '"Denied—your boots squeak uncertainty."',
  '"Yes—after Wing sends guidance."',
  '"No—guidance is “forthcoming.”"',
  '"Affirmative. The checklist is complete."',
  '"Negative. The checklist has more items."',
  '"Yes—if you brief it confidently."',
  '"No—you hesitated mid-brief."',
  '"Absolutely—your lanyard holds power."',
  '"Denied—lanyard energy insufficient."',
  '"Yes—if you double-check everything."',
  '"No—you triple-checked and still missed it."',
  '"Affirmative. The mission base approves."',
  '"Negative. Mission base is on lunch."',
  '"Is mayonnaise an instrument?"',
  '"No, this is Patrick!"',
  '"I love you."',
  '"The inner machinations of my mind are an enigma."',
  '"We should take Bikini Bottom and push it somewhere else!"',
  '"I can’t see my forehead."',
  '"Maybe it’s the way you’re dressed."',
  '"Firmly grasp it!"',
  '"I’m not a Krusty Krab."',
  '"Leedle leedle leedle lee!"',
  '"I wumbo, you wumbo, he she me wumbo."',
  '"That’s not my wallet."',
  '"Is this the Krusty Krab?"',
  '"I have no idea what’s going on."',
  '"Knowledge can never replace friendship."',
  '"We’re not just blowing bubbles, we’re making art!"',
  '"I don’t need it… I don’t need it… I definitely don’t need it… I NEED IT!"',
  '"Once there was an ugly barnacle. He was so ugly that everyone died. The end."',
  '"I thought of something funnier than 24… 25!"',
  '"East? I thought you said Weast."'
];

const form = document.getElementById('question-form');
const answerEl = document.getElementById('answer');

form.addEventListener('submit', (event) => {
  event.preventDefault();

  const randomIndex = Math.floor(Math.random() * outlandishResponses.length);
  answerEl.textContent = outlandishResponses[randomIndex];
});
